// Quantaureum Node source, version 1.0.0.
package qtd

import (
	"crypto/rand"
	"fmt"

	"github.com/cloudflare/circl/sign/dilithium/mode3"
)

// ⚠️  TSS-R7-01 (2026-07-17) — SIMULATED DISTRIBUTED DKG (TRUSTED DEALER):
//
// GenerateDKGDistributedSimulated is the SIMULATED single-process version of
// distributed DKG. It does NOT eliminate the trusted-dealer trust model: the
// calling process samples, aggregates, and Shamir-splits ALL participants'
// shares in one address space, then returns []*QTDShare containing EVERY
// participant's share. The TSSManager holding this slice can Lagrange-
// interpolate the full private key s1. This is functionally equivalent to a
// trusted dealer that immediately splits the key — useful for testing and
// for offline key ceremonies, but NOT a real multi-party DKG.
//
// The function is retained (renamed from GenerateDKGDistributed) for two
// narrow use cases:
//
//  1. TSSManager integration tests that need a programmatically-generated
//     group key without ceremony infrastructure.
//  2. Offline key ceremonies on air-gapped hosts, where the operator
//     explicitly accepts the trusted-dealer risk (gated by the
//     QAU_ALLOW_TRUSTED_DEALER_CEREMONY env var at the TSSManager layer).
//
// Production mainnet MUST NOT invoke this at runtime — mainnet validators
// import pre-generated shares via TSSKeyShareFile (enforced by the hard
// guard in node/config.go Validate()).
//
// ── What this function actually does ─────────────────────────────────────
//
//  1. Each participant i independently samples s1_i ∈ R_q^L and s2_i ∈ R_q^K
//     with small coefficients in [-eta, eta] (matching Dilithium3 secret-key
//     distribution). These are generated from independent crypto/rand
//     streams — no single seed captures them.
//  2. The function aggregates s1 = Σ s1_i and s2 = Σ s2_i IN THIS PROCESS.
//     In a real multi-party deployment, each participant would broadcast a
//     Pedersen commitment to their (s1_i, s2_i) and privately send the
//     actual values to a DKG coordinator. Here we simulate this in a single
//     process — see the CAVEAT below.
//  3. Computes t = A·s1 + s2 in R_q using the public matrix A derived from
//     rho (a fresh 32-byte public seed).
//  4. Splits t into (t0, t1) via Power2Round: t = t1·2^D + t0.
//  5. Splits s1, s2, t0 into Shamir shares over GF(Q) — any threshold
//     participants can reconstruct, but no subset smaller than threshold
//     learns anything.
//  6. Constructs the group public key from rho + packed t1 via
//     mode3.PublicKey.Unpack. CombinedSeed is set to nil: no seed exists
//     that can reconstruct the key via mode3.NewKeyFromSeed.
//
// ── Security properties (vs trusted-dealer WITH seed) ───────────────────
//
//   - No seed captures the full key. CombinedSeed = nil.
//   - The full s1, s2, t0 exist only transiently during aggregation and
//     are zeroized before the function returns.
//   - Signing MUST use the distributed TSS path (QTDSession.Round2Reveal
//     aggregation). GMQTD_SingleSign CANNOT be used (no full sk available).
//
// ── Why this is NOT a real distributed DKG (TSS-R7-01 finding) ──────────
//
// CAVEAT (single-process simulation): When called in a single process, the
// aggregated s1/s2/t0 do briefly coexist in memory. More fundamentally, the
// returned []*QTDShare contains ALL participants' shares, so whoever holds
// the slice can reconstruct the full key at any later time. The threshold
// property holds only EXTERNALLY to this function — i.e., when shares are
// distributed to separate processes and the caller discards its copy. The
// function itself provides no enforcement of this.
//
// ── Closure path (not yet implemented) ──────────────────────────────────
//
// The future P2P closure is defined by the DistributedDKGRunner interface
// (see dkg_runner.go in this package). It specifies a multi-round protocol
// in which each participant runs the per-party sampling locally and the
// coordinator only sees Pedersen commitments + A·s1_i + s2_i contributions.
// The math is identical to this function; only the network transport
// differs. Until the P2P runner is implemented, this simulated function
// remains the only programmatically-usable DKG path.
//
// REQUIRES threshold >= 2: A 1-of-n threshold would put the entire key in a
// single share, defeating the purpose of DKG.
func GenerateDKGDistributedSimulated(threshold, total int) (*QTDPublicKey, []*QTDShare, error) {
	if threshold <= 0 || total <= 0 || threshold > total {
		return nil, nil, ErrInvalidConfig
	}
	if threshold < 2 {
		return nil, nil, fmt.Errorf("distributed DKG requires threshold >= 2 for security (got %d)", threshold)
	}

	// Phase 1: Generate the public seed rho (32 bytes).
	//
	// TSS-M1 (R8 2026-07-19) — KNOWN LIMITATION (formally documented):
	// rho is generated by a SINGLE PARTY (the caller of this function) via
	// crypto/rand, NOT by a distributed commit-reveal coin-flipping protocol
	// among participants. The caller therefore has brief sole knowledge of
	// rho before it is broadcast (as part of the QTDPublicKey) to other
	// participants. This has two consequences:
	//
	//   1. Bias attack window: A malicious caller could in principle keep
	//      sampling rho until the resulting matrix A = ExpandA(rho) has
	//      some advantageous structure (e.g., low hamming weight rows that
	//      simplify finding collisions or approximations of A·s1). No
	//      known practical attack exploits this in Dilithium3's parameter
	//      regime — A is uniformly random in R_q^{K×L} and rho has 256
	//      bits of entropy, so the search space for any structured rho is
	//      cryptographically infeasible (~2^128 attempts to find a single
	//      chosen-bit-pattern rho). The risk is theoretical.
	//
	//   2. Premature knowledge: A caller who knows rho before the other
	//      participants could pre-compute A and start searching for s1
	//      candidates before others begin. This gives a negligible timing
	//      advantage only — the security of Dilithium3 does not depend on
	//      the secrecy of A, only on the secrecy of (s1, s2, t0). Once the
	//      key is generated, A is public anyway (it's part of the public
	//      key).
	//
	// Why we accept this for now: Implementing a commit-reveal coin-flip
	// for rho (e.g., Pi-protocol or Feldman-style verifiable randomness)
	// requires a multi-round P2P transport that the DistributedDKGRunner
	// interface (see dkg_runner.go) is designed to provide but is not yet
	// implemented. Production mainnet does NOT invoke
	// GenerateDKGDistributedSimulated at runtime — mainnet validators
	// import pre-generated shares via TSSKeyShareFile (enforced by the
	// hard guard in node/config.go Validate()), so the trust model for
	// rho generation is "key ceremony operator" rather than "any single
	// validator". This is acceptable because the ceremony operator is
	// already trusted with far more (e.g., verifying the absence of
	// backdoors in circl, choosing secure hash functions, etc.).
	//
	// Future closure: When a real P2P DKG runner is implemented
	// (DistributedDKGRunner.IsPlaceholder() == false), it MUST use a
	// commit-reveal or VRF-based protocol for rho generation so no single
	// party can bias A. The runner interface will need an additional
	// method (e.g., GenerateRhoDistributed) that this function will call
	// instead of crypto/rand.
	var rho [32]byte
	if _, err := rand.Read(rho[:]); err != nil {
		return nil, nil, fmt.Errorf("distributed DKG: failed to generate rho: %w", err)
	}

	// Phase 2: Each participant i independently samples s1_i and s2_i with
	// small coefficients in [-eta, eta]. The per-participant material is
	// zeroized immediately after aggregation so it cannot be recovered.
	s1Vec := make(PolyVec, Dilithium3L) // s1 = Σ s1_i
	s2Vec := make(PolyVec, Dilithium3K) // s2 = Σ s2_i
	for pid := 1; pid <= total; pid++ {
		s1I, err := sampleSmallPolyVec(Dilithium3L, Dilithium3EtaPoly)
		if err != nil {
			return nil, nil, fmt.Errorf("distributed DKG: participant %d s1_i: %w", pid, err)
		}
		s2I, err := sampleSmallPolyVec(Dilithium3K, Dilithium3EtaPoly)
		if err != nil {
			return nil, nil, fmt.Errorf("distributed DKG: participant %d s2_i: %w", pid, err)
		}
		for j := range s1Vec {
			s1Vec[j].Add(&s1Vec[j], &s1I[j])
		}
		for j := range s2Vec {
			s2Vec[j].Add(&s2Vec[j], &s2I[j])
		}
		// Zeroize per-participant material — no longer needed after aggregation.
		for j := range s1I {
			zeroPolyFunc(&s1I[j])
		}
		for j := range s2I {
			zeroPolyFunc(&s2I[j])
		}
	}

	// Phase 3: Compute t = A·s1 + s2 in R_q.
	aMat, err := ComputeA(rho[:], Dilithium3K, Dilithium3L)
	if err != nil {
		return nil, nil, fmt.Errorf("distributed DKG: ComputeA: %w", err)
	}
	tVec := ComputeW(aMat, s1Vec) // t = A·s1
	for i := range tVec {
		tVec[i].Add(&tVec[i], &s2Vec[i]) // t = A·s1 + s2
		tVec[i].Reduce()                 // normalize to [0, Q-1]
	}

	// Phase 4: Power2Round — split t into (t1, t0) such that t = t1·2^D + t0.
	// t1Vec[i][c] ∈ [0, 2^10 - 1] is public (goes into the Dilithium3 public key).
	// t0Vec[i][c] stores Q + t0 (circl format), with t0 ∈ (-2^(D-1), 2^(D-1)].
	t1Vec := make(PolyVec, Dilithium3K)
	t0Vec := make(PolyVec, Dilithium3K)
	for i := range tVec {
		Power2RoundPoly(&t0Vec[i], &t1Vec[i], &tVec[i])
	}

	// Phase 5: Pack t1 into the circl Dilithium3 public-key format and
	// construct a mode3.PublicKey via Unpack. This validates that t1Vec is
	// in the correct range [0, 1023]; if Power2Round is correct, this will
	// always succeed.
	t1Packed := PackT1Vec(t1Vec)
	if len(t1Packed) != Dilithium3K*320 {
		return nil, nil, fmt.Errorf("distributed DKG: t1 packed size mismatch: got %d, want %d",
			len(t1Packed), Dilithium3K*320)
	}
	var pkBuf [mode3.PublicKeySize]byte
	copy(pkBuf[:32], rho[:])
	copy(pkBuf[32:], t1Packed)
	var pubKey mode3.PublicKey
	pubKey.Unpack(&pkBuf)

	// Phase 6: Shamir split s1, s2, t0 — each coefficient independently
	// shared over GF(Q). Any threshold participants can reconstruct.
	s1ShareVecs, err := shamirSplitPolyVec(s1Vec, threshold, total)
	if err != nil {
		return nil, nil, fmt.Errorf("distributed DKG: Shamir split s1: %w", err)
	}
	s2ShareVecs, err := shamirSplitPolyVec(s2Vec, threshold, total)
	if err != nil {
		return nil, nil, fmt.Errorf("distributed DKG: Shamir split s2: %w", err)
	}
	t0ShareVecs, err := shamirSplitPolyVec(t0Vec, threshold, total)
	if err != nil {
		return nil, nil, fmt.Errorf("distributed DKG: Shamir split t0: %w", err)
	}

	// Phase 7: Build QTDShare per participant with Pedersen verification
	// vectors for s1, s2, and t0. Each vector is generated independently
	// per share and per secret type so that VerifyShare can later attest
	// to the consistency of all three.
	shares := make([]*QTDShare, total)
	for i := 0; i < total; i++ {
		pid := i + 1
		shares[i] = &QTDShare{
			ParticipantID: pid,
			Rho:           append([]byte(nil), rho[:]...),
			S1ShareBytes:  VecToBytes(s1ShareVecs[pid]),
			S2ShareBytes:  VecToBytes(s2ShareVecs[pid]),
			T0ShareBytes:  VecToBytes(t0ShareVecs[pid]),
			VVector:       nil,
		}

		vVector, verr := generateVerificationVector(shares[i].S1ShareBytes, threshold)
		if verr != nil {
			return nil, nil, fmt.Errorf("distributed DKG: VVector s1 (pid %d): %w", pid, verr)
		}
		shares[i].VVector = vVector

		vVectorS2, verr2 := generateVerificationVector(shares[i].S2ShareBytes, threshold)
		if verr2 != nil {
			return nil, nil, fmt.Errorf("distributed DKG: VVector s2 (pid %d): %w", pid, verr2)
		}
		shares[i].VVectorS2 = vVectorS2

		vVectorT0, verr3 := generateVerificationVector(shares[i].T0ShareBytes, threshold)
		if verr3 != nil {
			return nil, nil, fmt.Errorf("distributed DKG: VVector t0 (pid %d): %w", pid, verr3)
		}
		shares[i].VVectorT0 = vVectorT0
	}

	// Phase 8: Each share gets its own copy of T1Bytes (the packed public t1).
	// audit-fix L5-007: avoid shared slice aliasing — each share must own its copy.
	for i := 0; i < total; i++ {
		t1Copy := make([]byte, len(t1Packed))
		copy(t1Copy, t1Packed)
		shares[i].T1Bytes = t1Copy
	}

	// Phase 9: Zeroize aggregated secrets. After this point, the function
	// only holds Shamir shares — no single participant's material can
	// reconstruct the full key.
	for i := range s1Vec {
		zeroPolyFunc(&s1Vec[i])
	}
	for i := range s2Vec {
		zeroPolyFunc(&s2Vec[i])
	}
	for i := range t0Vec {
		zeroPolyFunc(&t0Vec[i])
	}
	for i := range tVec {
		zeroPolyFunc(&tVec[i])
	}

	qtdPubKey := &QTDPublicKey{
		Rho:          append([]byte(nil), rho[:]...),
		T1:           append([]byte(nil), t1Packed...),
		PubKey:       append([]byte(nil), pubKey.Bytes()...),
		CombinedSeed: nil, // No seed — distributed DKG has no single seed
	}
	return qtdPubKey, shares, nil
}

// Power2RoundPoly splits each coefficient of p into (p0PlusQ, p1) such that
//
//	p[i] = p1[i] * 2^D + p0[i]   with -2^(D-1) < p0[i] ≤ 2^(D-1).
//
// p0PlusQ[i] = Q + p0[i] (matches circl's internal representation: coefficients
// lie in (Q - 2^(D-1), Q + 2^(D-1)] and are NOT normalized to [0, Q-1]).
// p1[i] ∈ [0, 2^10 - 1].
//
// Input p must be normalized to [0, Q-1].
//
// TSS-R5-03/04 FIX: This is the missing primitive that prevented real
// distributed DKG. Without it, the codebase could only obtain (t0, t1) by
// calling mode3.NewKeyFromSeed — which requires the full seed and
// materializes the complete private key. With Power2RoundPoly, we can
// derive (t0, t1) directly from t = A·s1 + s2, computed from distributed
// shares, without ever invoking the seed-based key generation.
//
// The implementation matches circl's internal power2round (sign/internal/
// dilithium/field.go:35) bit-for-bit, ensuring binary compatibility with
// mode3.PublicKey.Unpack and mode3.PrivateKey.Unpack.
func Power2RoundPoly(p0PlusQ, p1, p *Poly) {
	for i := 0; i < N; i++ {
		a0PlusQ, a1 := power2round(uint32(p[i]))
		p0PlusQ[i] = int32(a0PlusQ)
		p1[i] = int32(a1)
	}
}

// power2round splits a ∈ [0, Q-1] into (a0plusQ, a1) such that
//
//	a = a1 * 2^D + a0   with -2^(D-1) < a0 ≤ 2^(D-1).
//
// Returns a0plusQ = Q + a0 (circl's representation) and a1 ∈ [0, 2^10 - 1].
// Matches circl's internal power2round (sign/internal/dilithium/field.go:35).
func power2round(a uint32) (a0plusQ, a1 uint32) {
	a0 := a & ((1 << Dilithium3D) - 1) // a mod 2^D, ∈ [0, 2^D - 1]
	// Shift to centered representation via the circl trick.
	a0 -= (1 << (Dilithium3D - 1)) + 1
	a0 += uint32(int32(a0)>>31) & (1 << Dilithium3D)
	a0 -= (1 << (Dilithium3D - 1)) - 1
	a0plusQ = uint32(Q) + a0
	a1 = (a - a0) >> Dilithium3D
	return
}

// PackT1 packs a single t1 polynomial into buf (must be 320 bytes).
// Coefficients of p must be in [0, 2^10 - 1].
// Matches circl's Poly.PackT1 (sign/internal/dilithium/pack.go:88).
//
// TSS-R5-03/04 FIX: Provides the inverse of UnpackT1, which was missing
// from the qtd package. Required to build a mode3.PublicKey from a t1
// polynomial vector computed via Power2Round during distributed DKG.
func PackT1(p *Poly, buf []byte) {
	const polyT1Size = 320
	if len(buf) < polyT1Size {
		return
	}
	j := 0
	for i := 0; i < polyT1Size; i += 5 {
		buf[i] = byte(p[j])
		buf[i+1] = byte(p[j]>>8) | byte(p[j+1]<<2)
		buf[i+2] = byte(p[j+1]>>6) | byte(p[j+2]<<4)
		buf[i+3] = byte(p[j+2]>>4) | byte(p[j+3]<<6)
		buf[i+4] = byte(p[j+3] >> 2)
		j += 4
	}
}

// PackT1Vec packs a PolyVec of K polynomials into 320*K bytes (the circl
// Dilithium3 public-key t1 layout). Returns nil if vec is empty.
func PackT1Vec(vec PolyVec) []byte {
	if len(vec) == 0 {
		return nil
	}
	out := make([]byte, 320*len(vec))
	for i := range vec {
		PackT1(&vec[i], out[i*320:(i+1)*320])
	}
	return out
}

// sampleSmallPolyVec samples a PolyVec of numPolys polynomials with
// coefficients uniformly distributed in [-eta, eta] using rejection sampling
// from crypto/rand. Matches the Dilithium3 secret-key coefficient
// distribution (eta = 4 for mode3, so coefficients ∈ {-4, -3, ..., 3, 4}).
//
// Output coefficients are stored in canonical [0, Q-1] form: negative values
// are wrapped via +Q so the result is directly usable in Poly.Add etc.
//
// SECURITY: Uses crypto/rand, NOT a deterministic seed. Each call produces
// independent random output. This is the per-participant sampling that
// makes GenerateDKGDistributedSimulated's per-party contributions independent
// (no master seed reconstructs the aggregated s1/s2). Note: this property
// alone does NOT make the function a real distributed DKG — see the
// function's CAVEAT about the single-process aggregation.
func sampleSmallPolyVec(numPolys, eta int) (PolyVec, error) {
	if eta <= 0 {
		return nil, fmt.Errorf("sampleSmallPolyVec: eta must be > 0, got %d", eta)
	}
	vec := make(PolyVec, numPolys)
	// Rejection sampling: 2*eta+1 values are valid. We sample a byte and
	// accept if it falls in the largest multiple of (2*eta+1) below 256.
	// For eta=4, 2*eta+1 = 9, and 256 / 9 = 28, so we accept r < 28*9 = 252.
	// This gives a perfectly uniform distribution with ~1.6% rejection rate.
	rangeSize := uint32(2*eta + 1)
	acceptBound := (256 / rangeSize) * rangeSize

	const batchSize = 4096
	var batch [batchSize]byte
	off := len(batch) // start exhausted to trigger first fill

	for p := 0; p < numPolys; p++ {
		for c := 0; c < N; c++ {
			var val int32
			for {
				if off >= len(batch) {
					if _, err := rand.Read(batch[:]); err != nil {
						return nil, fmt.Errorf("sampleSmallPolyVec: rand.Read: %w", err)
					}
					off = 0
				}
				r := uint32(batch[off])
				off++
				if r < acceptBound {
					val = int32(r%rangeSize) - int32(eta)
					break
				}
			}
			// Wrap negative values to [0, Q-1].
			if val < 0 {
				vec[p][c] = int32(Q) + val
			} else {
				vec[p][c] = val
			}
		}
	}
	return vec, nil
}
